version: '3'

services:
  sse-chat-nginx:
    image: nginx:1.27.0
    container_name: sse-chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www
    depends_on:
      - sse-chat-php
      - sse-chat-redis
    networks:
      - local_host

  sse-chat-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sse-chat-php
    ports:
      - 8081:8081
    volumes:
      - ../:/var/www
    stdin_open: true
    tty: true
    working_dir: /var/www
    restart: always
    networks:
      - local_host

  sse-chat-redis:
    container_name: sse-chat-redis
    image: redis:alpine
    ports:
      - 16379:6379
    restart: always
    networks:
      - local_host

networks:
  local_host:
    driver: bridge
